openapi: 3.0.0
info:
  title: API documentation of fundbox24's backend
  version: 1.0.0
tags:
  - name: User management
  - name: Report
  - name: Chat

paths:
  /users:
    get:
      tags:
        - User management
      summary: Get a list of all users
      description: Returns a list of all users. You won't get the passwords. This endpoint is only accessible to admin users.
      responses:
        '200':
          description: Successfully listed a user
    post:
      tags:
        - User management
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Successfully created a user

  /users/{email}:
    get:
      tags:
        - User management
      summary: Get a user by Email
      description: Returns a user by Email. You won't get the password.
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user
          schema:
            type: string
            minimum: 0
      responses:
        '200':
          description: Successfully retrieved a user
    put:
      tags:
        - User management
      summary: Update a user by Email
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user
          schema:
            type: string
            minimum: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successfully updated a user
    delete:
      tags:
        - User management
      summary: Delete a user by Email
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user
          schema:
            type: string
            minimum: 0
      responses:
        '200':
          description: Successfully deleted a user

  /user/{email}/authenticate:
    post:
      tags:
        - User management
      summary: Authenticate a user
      description: Authenticate a user by email and password
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user
          schema:
            type: string
            minimum: 0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: Successfully authenticated a user
  /report:
    get:
      tags:
        - Report
      summary: Get a list of all reports
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
      responses:
        '200':
          description: Successfully listed a report

  /report/found:
    get:
      tags:
        - Report
      summary: Get a list of all found reports
      responses:
        '200':
          description: Successfully listed a report
    post:
      tags:
        - Report
      summary: Create a new found report
      responses:
        '201':
          description: Successfully created a report

  /report/found/{id}:
    put:
      tags:
        - Report
      summary: Update a found report
      responses:
        '200':
          description: Successfully updated a report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                object:
                  type: string
                description:
                  type: string
                status:
                  type: string
                place_of_discovery:
                  type: string
                datetime_of_discovery:
                  type: string
                place_of_delivery:
                  type: string
    delete:
      tags:
        - Report
      summary: Delete a found report
      responses:
        '200':
          description: Successfully deleted a report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                object:
                  type: string
                description:
                  type: string
                status:
                  type: string
                place_of_discovery:
                  type: string
                datetime_of_discovery:
                  type: string
                place_of_delivery:
                  type: string

  /report/lost:
    get:
      tags:
        - Report
      summary: Get a list of all lost reports
      responses:
        '200':
          description: Successfully listed a report

  /chat:
    get:
      tags:
        - Chat
      summary: Get a list of all messages
      responses:
        '200':
          description: Successfully listed a message
    post:
      tags:
        - Chat
      summary: Create a new message
      responses:
        '201':
          description: Successfully created a message

  /chat/{id}:
    put:
      tags:
        - Chat
      summary: Update a message
      responses:
        '200':
          description: Successfully updated a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                type:
                  type: string
                content:
                  type: string
                createdAt:
                  type: string
    delete:
      tags:
        - Chat
      summary: Delete a message
      responses:
        '200':
          description: Successfully deleted a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                type:
                  type: string
                content:
                  type: string
                createdAt:
                  type: string


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          required: true
          readOnly: true
          uniqueItems: true
          description: The user ID
        email:
          type: string
          required: true
          uniqueItems: true
          description: The user's email
        password:
          type: string
          required: true
          description: The user's password
        username:
          type: string
          required: true
          description: The user's username
        firstname:
          type: string
          required: true
          description: The user's first name
        lastname:
          type: string
          required: true
          description: The user's last name

    Report:
      type: object
      properties:
        id:
          type: integer
          minimum: 0
        title:
          type: string
          minLength: 1
          maxLength: 300
        user:
          type: string
          minLength: 1
          maxLength: 100

    Message:
      type: object
      properties:
        id:
          type: integer
          minimum: 0
        type:
          type: string
          minLength: 1
          maxLength: 300
        content:
          type: string
          minLength: 1
          maxLength: 100
        createdAt:
          type: string
